name: Update Json API

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install PyGithub requests

      - name: Verificar se houve mudança
        run: |
          if git diff --quiet data.json; then
            echo "Nenhuma mudança detectada."
            echo "skip_commit=true" >> $GITHUB_ENV
          else
            echo "Mudanças detectadas!"
            echo "skip_commit=false" >> $GITHUB_ENV
          fi

      - name: Atualizar JSON
        run: |
          python update.py

      - name: Commit e push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dados.json
          git commit -m "Atualizando dados.json automaticamente"
          git push
